# Generated by Django 4.2.23 on 2025-07-13 08:17

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aadiscordbot", "0016_authbotconfiguration_admin_user_ids_and_more"),
        ("tnnt_discordbot_cogs", "0002_setting_lookup_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="locate_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Channels in which the `/locate` command can be used.",
                related_name="locate_channels",
                to="aadiscordbot.channels",
                verbose_name="Locate Channels",
            ),
        ),
    ]
