# Generated by Django 5.2.16 on 2026-07-10 17:52

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupmanagement", "0021_alter_authgroup_group_and_more"),
        ("tnnt_discordbot_cogs", "0004_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="admin_god_group",
            field=models.OneToOneField(
                blank=True,
                help_text=(
                    "The group that has god mode access (Admin Mode) in all services. "
                    "Please ensure to give this group in all connected services the "
                    "appropriate privileges."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_god_group",
                to="groupmanagement.group",
                verbose_name="Admin God Group",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="admin_gods",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "These users are eligible to invoke the god commands of the "
                    "Discordbot to promote/demote themself to/from god."
                ),
                related_name="admin_god",
                to="authentication.user",
                verbose_name="Admin Gods",
            ),
        ),
    ]
