# Generated by Django 5.2.16 on 2026-07-19 07:20

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aadiscordbot", "0017_alter_authbotconfiguration_options_and_more"),
        ("tnnt_discordbot_cogs", "0005_setting_admin_god_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="honeypot_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text='Channels that are monitored for the "honeypot" feature. Any user that posts in these channels will be banned.',
                related_name="honeypot_channels",
                to="aadiscordbot.channels",
                verbose_name="Honeypot Channels",
            ),
        ),
    ]
