# Generated by Django 5.2.17 on 2026-08-17 07:36

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aadiscordbot", "0017_alter_authbotconfiguration_options_and_more"),
        ("tnnt_discordbot_cogs", "0006_honeypot"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="honeypot_report_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="The channel where reports of users banned by the honeypot feature will be sent.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="honeypot_report_channel",
                to="aadiscordbot.channels",
                verbose_name="Honeypot Report Channel",
            ),
        ),
    ]
